## 姊妹篇   飞桨 推荐系统  suprise

数据来源
### https://grouplens.org/datasets/movielens/

- 基于内容推荐
- 基于用户推荐


- 矩阵分解

- 相似度
    -  欧式距离
    -  Jaccard相似
    -  COS相似
    -  pearson 相似

- item协同过滤和用户协同过滤   商品相似 和用户相似


- 冷启动code start 没有用户
    - 不设置推荐
    - 新上item（）
- gray sheep

- 商品,用户增加 复杂



- 总是给用户推荐相似的item


RMSE   平方 线下评估

MAE   绝对值

F1 & F2

recall & precision  召回率 


A/B testing


CTR  CR  点击率 Click through Rate  转换率  Conversion Rate   点了 并且很好的看完了，或者购买了









https://blog.csdn.net/mycafe_/article/details/79146764

https://blog.csdn.net/livan1234/article/details/85159859

In [3]:
import sys
sys.path

['',
 'E:\\ProgramData\\Anaconda3\\envs\\tensorflow\\python35.zip',
 'E:\\ProgramData\\Anaconda3\\envs\\tensorflow\\DLLs',
 'E:\\ProgramData\\Anaconda3\\envs\\tensorflow\\lib',
 'E:\\ProgramData\\Anaconda3\\envs\\tensorflow',
 'E:\\ProgramData\\Anaconda3\\envs\\tensorflow\\lib\\site-packages',
 'E:\\ProgramData\\Anaconda3\\envs\\tensorflow\\lib\\site-packages\\win32',
 'E:\\ProgramData\\Anaconda3\\envs\\tensorflow\\lib\\site-packages\\win32\\lib',
 'E:\\ProgramData\\Anaconda3\\envs\\tensorflow\\lib\\site-packages\\Pythonwin',
 'E:\\ProgramData\\Anaconda3\\envs\\tensorflow\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Administrator\\.ipython']

#### https://surprise.readthedocs.io/en/stable/getting_started.html#automatic-cross-validation

In [1]:
from surprise import SVD
from surprise import Dataset
from surprise.model_selection import cross_validate

# Load the movielens-100k dataset (download it if needed).
data = Dataset.load_builtin('ml-100k')

# Use the famous SVD algorithm.
algo = SVD()

# Run 5-fold cross-validation and print results.
cross_validate(algo, data, measures=['RMSE', 'MAE'], cv=5, verbose=True)

Evaluating RMSE, MAE of algorithm SVD on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std     
RMSE (testset)    0.9447  0.9369  0.9271  0.9373  0.9354  0.9363  0.0056  
MAE (testset)     0.7440  0.7408  0.7309  0.7397  0.7369  0.7385  0.0044  
Fit time          4.17    4.28    4.31    4.39    4.23    4.28    0.07    
Test time         0.45    0.14    0.12    0.12    0.13    0.19    0.13    


{'fit_time': (4.174954414367676,
  4.2758660316467285,
  4.306457042694092,
  4.393184185028076,
  4.234297752380371),
 'test_mae': array([0.74399127, 0.74081589, 0.73089697, 0.73967413, 0.73690273]),
 'test_rmse': array([0.94465655, 0.93686801, 0.92714499, 0.93725012, 0.93538114]),
 'test_time': (0.4523122310638428,
  0.1438910961151123,
  0.12382626533508301,
  0.12179899215698242,
  0.13284873962402344)}

#### 通过GridSearch获取最优参数

In [2]:
from surprise.model_selection import GridSearchCV

# 定义好需要优选的参数网格
param_grid = {'n_epochs': [5, 10], 'lr_all': [0.002, 0.005],
              'reg_all': [0.4, 0.6]}
# 使用网格搜索交叉验证
grid_search = GridSearchCV(SVD, param_grid, measures=['rmse', 'mae'])
# 在数据集上找到最好的参数
data = Dataset.load_builtin('ml-100k')
data.split(n_folds=3)
grid_search.fit(data)


In [3]:
# 输出调优的参数组 
# 输出最好的RMSE结果
print(grid_search.best_score['rmse'])
# >>> 0.96117566386

# 输出对应最好的RMSE结果的参数
print(grid_search.best_params['rmse'])
# >>> {'reg_all': 0.4, 'lr_all': 0.005, 'n_epochs': 10}

print(grid_search.best_score['mae'])
# >>> 0.7708418493208119

print(grid_search.best_params['mae'])
# >>> {'reg_all': 0.4, 'lr_all': 0.005, 'n_epochs': 10}

0.9610953501902442
{'reg_all': 0.4, 'lr_all': 0.005, 'n_epochs': 10}
0.7702132454853247
{'reg_all': 0.4, 'lr_all': 0.005, 'n_epochs': 10}


In [4]:
trainset = data
### 使用NormalPredictor
from surprise.model_selection import cross_validate

### 使用SVD
from surprise import SVD

# Use the famous SVD algorithm.
algo = SVD(reg_all=0.4,lr_all=0.005,n_epochs=10)
# Load the movielens-100k dataset (download it if needed).
data = Dataset.load_builtin('ml-100k')

# Run 5-fold cross-validation and print results.
cross_validate(algo, data, measures=['RMSE', 'MAE'], cv=5, verbose=True)

Evaluating RMSE, MAE of algorithm SVD on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std     
RMSE (testset)    0.9630  0.9671  0.9554  0.9572  0.9626  0.9611  0.0042  
MAE (testset)     0.7717  0.7743  0.7652  0.7690  0.7688  0.7698  0.0031  
Fit time          2.11    2.08    2.08    2.19    2.19    2.13    0.05    
Test time         0.14    0.14    0.11    0.15    0.12    0.13    0.01    


{'fit_time': (2.1100995540618896,
  2.0780038833618164,
  2.08200740814209,
  2.188826322555542,
  2.1888129711151123),
 'test_mae': array([0.77167004, 0.77433   , 0.76519689, 0.76901907, 0.76883135]),
 'test_rmse': array([0.96304559, 0.96705748, 0.95542005, 0.95721594, 0.96262451]),
 'test_time': (0.13787269592285156,
  0.13635873794555664,
  0.10630512237548828,
  0.1463911533355713,
  0.12081789970397949)}

In [5]:
from surprise import accuracy
from surprise.model_selection import train_test_split

# Load the movielens-100k dataset (download it if needed),
data = Dataset.load_builtin('ml-100k')

# sample random trainset and testset
# test set is made of 25% of the ratings.
trainset, testset = train_test_split(data, test_size=.25)

# We'll use the famous SVD algorithm.
algo = SVD(reg_all=0.4,lr_all=0.005,n_epochs=10)

# Train the algorithm on the trainset, and predict ratings for the testset
algo.fit(trainset)
predictions = algo.test(testset)

# Then compute RMSE
(accuracy.rmse(predictions),accuracy.mae(predictions))


RMSE: 0.9591
MAE:  0.7678


(0.9591376451476961, 0.7678210050955677)

In [6]:
uid = str(196)  # raw user id (as in the ratings file). They are **strings**!
iid = str(302)  # raw item id (as in the ratings file). They are **strings**!

# get a prediction for specific users and items.
pred = algo.predict(uid, iid, r_ui=4, verbose=True)

user: 196        item: 302        r_ui = 4.00   est = 4.15   {'was_impossible': False}


## 基于sk-suprise 对 ml-latest-small 进行推荐

In [7]:
import pandas as pd
import numpy as np

In [8]:
ratings_df = pd.read_csv('./ml-latest-small/ratings.csv')


In [9]:
ratings_df.tail()

userId  movieId  rating   timestamp
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

In [10]:
movies_df = pd.read_csv("./ml-latest-small/movies.csv")


In [11]:
movies_df['movieRow'] = movies_df.index

In [12]:
movies_df.tail()

movieId                                      title  \
9737   193581  Black Butler: Book of the Atlantic (2017)   
9738   193583               No Game No Life: Zero (2017)   
9739   193585                               Flint (2017)   
9740   193587        Bungo Stray Dogs: Dead Apple (2018)   
9741   193609        Andrew Dice Clay: Dice Rules (1991)   

                               genres  movieRow  
9737  Action|Animation|Comedy|Fantasy      9737  
9738         Animation|Comedy|Fantasy      9738  
9739                            Drama      9739  
9740                 Action|Animation      9740  
9741                           Comedy      9741

In [13]:
movies_df = movies_df[['movieRow','movieId','title']]
movies_df.to_csv('./ml-latest-small/moviesProcess.csv',index=False,header=True,encoding='utf-8')


In [14]:
movies_df.tail()

movieRow  movieId                                      title
9737      9737   193581  Black Butler: Book of the Atlantic (2017)
9738      9738   193583               No Game No Life: Zero (2017)
9739      9739   193585                               Flint (2017)
9740      9740   193587        Bungo Stray Dogs: Dead Apple (2018)
9741      9741   193609        Andrew Dice Clay: Dice Rules (1991)

In [15]:
ratings_df = pd.merge(ratings_df,movies_df,on='movieId')


In [16]:
ratings_df.tail()

userId  movieId  rating   timestamp  movieRow  \
100831     610   160341     2.5  1479545749      9325   
100832     610   160527     4.5  1479544998      9330   
100833     610   160836     3.0  1493844794      9342   
100834     610   163937     3.5  1493848789      9389   
100835     610   163981     3.5  1493850155      9390   

                                   title  
100831                  Bloodmoon (1997)  
100832  Sympathy for the Underdog (1971)  
100833                     Hazard (2005)  
100834                Blair Witch (2016)  
100835                         31 (2016)

In [17]:
ratings_df = ratings_df[['userId','movieRow','rating']]
ratings_df.to_csv('./ml-latest-small/ratingsProcess.csv',index=False,header=True,encoding='utf-8')


In [18]:
ratings_df.head()

userId  movieRow  rating
0       1         0     4.0
1       5         0     4.0
2       7         0     4.5
3      15         0     2.5
4      17         0     4.5

In [19]:
ratings_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100836 entries, 0 to 100835
Data columns (total 3 columns):
userId      100836 non-null int64
movieRow    100836 non-null int64
rating      100836 non-null float64
dtypes: float64(1), int64(2)
memory usage: 3.1 MB


## 矩阵

In [20]:
userNo = ratings_df['userId'].max()+1
movieNo = ratings_df['movieRow'].max() +1

In [21]:
userNo

611

In [22]:
movieNo

9742

In [23]:
rating = np.zeros((movieNo,userNo))

In [24]:
flag = 0
ratings_df_length =  np.shape(ratings_df)[0]
for index,row in ratings_df.iterrows():
    rating[int(row['movieRow']),int(row['userId'])] = row["rating"]
    flag +=1
    #print('process %d,%d'%(flag,ratings_df_length-flag))
    


In [25]:
record = rating>0
record

array([[False,  True, False, ...,  True,  True,  True],
       [False, False, False, ...,  True, False, False],
       [False,  True, False, ...,  True, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [26]:
record = np.array(record,dtype=int)

In [27]:
record

array([[0, 1, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 1, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

## 构建模型

In [ ]:
from surprise import SVD
from surprise import Dataset
from surprise.model_selection import cross_validate
from surprise import accuracy
from surprise.model_selection import train_test_split


### 看原来的数据结构

In [29]:

# 首先，用算法计算相互间的相似度
data = Dataset.load_builtin('ml-100k')
trainset = data.build_full_trainset()

In [30]:
(trainset.all_users(),trainset.all_items())

(range(0, 943), range(0, 1682))

In [31]:
trainset.all_ratings()

<generator object Trainset.all_ratings at 0x0000014F0DC6CB48>

In [32]:
ratings_df.head()

userId  movieRow  rating
0       1         0     4.0
1       5         0     4.0
2       7         0     4.5
3      15         0     2.5
4      17         0     4.5

In [33]:
movies_df.head()


movieRow  movieId                               title
0         0        1                    Toy Story (1995)
1         1        2                      Jumanji (1995)
2         2        3             Grumpier Old Men (1995)
3         3        4            Waiting to Exhale (1995)
4         4        5  Father of the Bride Part II (1995)

In [34]:
movies_df.loc

### 使用模拟的数据组成 user-item-rating数据

In [133]:
from surprise import Reader
# A reader is still needed but only the rating_scale param is requiered.
reader = Reader(rating_scale=(1, 5))
# The columns must correspond to user id, item id and ratings (in that order).
data = Dataset.load_from_df(ratings_df[['userId', 'movieRow', 'rating']], reader)


## SVD最优参数 并fit data

In [157]:
from surprise.model_selection import GridSearchCV
### 使用SVD
from surprise import SVD

# 定义好需要优选的参数网格
param_grid = {'n_epochs': [5, 10], 'lr_all': [0.002, 0.005],
              'reg_all': [0.4, 0.6]}
# 使用网格搜索交叉验证
grid_search = GridSearchCV(SVD, param_grid, measures=['rmse', 'mae'])
# 在数据集上找到最好的参数
data.split(n_folds=3)
grid_search.fit(data)


In [160]:

print(grid_search.best_params['rmse'])
print(grid_search.best_params['mae'])

{'reg_all': 0.4, 'lr_all': 0.005, 'n_epochs': 10}
{'reg_all': 0.4, 'lr_all': 0.005, 'n_epochs': 10}


In [137]:

# Use the famous SVD algorithm.
algo = SVD(reg_all=0.4,lr_all=0.005,n_epochs=10)

In [138]:
cross_validate(algo, data, cv=5)

{'fit_time': (2.2570178508758545,
  2.286081314086914,
  2.347818374633789,
  2.3522582054138184,
  2.346250295639038),
 'test_mae': array([0.68308454, 0.68906554, 0.69244549, 0.69194282, 0.69180421]),
 'test_rmse': array([0.88837928, 0.89037157, 0.89398886, 0.8902951 , 0.89365214]),
 'test_time': (0.1152944564819336,
  0.1303551197052002,
  0.18950414657592773,
  0.17446517944335938,
  0.1769707202911377)}

In [139]:
cross_validate(SVD(), data, cv=5)

{'fit_time': (4.480921506881714,
  4.5280468463897705,
  4.505008697509766,
  4.493027687072754,
  4.552611827850342),
 'test_mae': array([0.67664913, 0.6693639 , 0.66712796, 0.67148302, 0.67201217]),
 'test_rmse': array([0.88462873, 0.87067839, 0.86948172, 0.87498782, 0.8706602 ]),
 'test_time': (0.18499398231506348,
  0.11630964279174805,
  0.1368403434753418,
  0.1789684295654297,
  0.18201184272766113)}

In [140]:
trainset = data.build_full_trainset()
algo.fit(trainset)

In [142]:
# 另一个KNN算法
#trainset = data.build_full_trainset()

from surprise import KNNBaseline
knn = KNNBaseline()
knn.fit(trainset)

Estimating biases using als...
Computing the msd similarity matrix...
Done computing similarity matrix.


### 预测和电影相似的电影

In [143]:

mov_id = 1
# Retrieve inner ids of the nearest neighbors of Toy Story.
toy_story_neighbors = knn.get_neighbors(mov_id, k=10)

# Convert inner ids of the neighbors into names.
print('The 10 nearest neighbors of %s  are:' %(movies_df.iloc[mov_id]['title']))
print(u'最相似的10部电影是：'.center(80, '='))
# 获取电影名到电影id 和 电影id到电影名的映射
for i in toy_story_neighbors:
    #print(u'评分: %.2f, 电影名: %s' % (predicts[i, int(user_id)]-2, movies.iloc[i]['title']))
    print(u'    电影名: %s' % ( movies_df.iloc[i]['title']))
    

The 10 nearest neighbors of Jumanji (1995)  are:
==================================最相似的10部电影是：===================================
    电影名: Happy Gilmore (1996)
    电影名: Tales from the Hood (1995)
    电影名: Last Supper, The (1995)
    电影名: Bad Girls (1994)
    电影名: Bloodsport 2 (a.k.a. Bloodsport II: The Next Kumite) (1996)
    电影名: Tales from the Crypt Presents: Demon Knight (1995)
    电影名: Solo (1996)
    电影名: What's Eating Gilbert Grape (1993)
    电影名: Beverly Hills Cop III (1994)
    电影名: Even Cowgirls Get the Blues (1993)


In [39]:
toy_story_neighbors = algo.get_neighbors(1, k=10)


In [40]:
toy_story_neighbors

[101, 108, 126, 172, 272, 316, 461, 463, 491, 493]

In [41]:
movies_df.iloc[1]

movieRow                 1
movieId                  2
title       Jumanji (1995)
Name: 1, dtype: object

In [42]:
pred = algo.predict(1, 2, r_ui=4, verbose=True)

user: 1          item: 2          r_ui = 4.00   est = 4.09   {'was_impossible': False, 'actual_k': 40}


In [43]:
pred = algo.predict(2, 1, r_ui=4, verbose=True)

user: 2          item: 1          r_ui = 4.00   est = 3.59   {'was_impossible': False, 'actual_k': 40}


##  根据user 预测item

### 构建一个新的数据从users 到items 的预测数据集

In [44]:
userNo,movieNo

(611, 9742)

In [177]:
#ratings_df.loc[0]

ratings_df.loc[ratings_df['userId']==3].loc[ratings_df['rating']>4.9]

userId  movieRow  rating
15986       3      2765     5.0
18195       3       656     5.0
18651       3      2141     5.0
18800       3      3335     5.0
18810       3      3734     5.0
18812       3      4045     5.0
18814       3      4122     5.0
18825       3      4595     5.0
18827       3      5080     5.0
18832       3      7114     5.0

In [178]:
ratings_df[ratings_df['userId']==3][ratings_df['movieRow']==656]

E:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


userId  movieRow  rating
18195       3       656     5.0

### 测试 用户3 到1,2,23，三个item的得分

In [144]:
predicts_base = [(3,1,0),(3,2,0),(3,23,0)]
algo.test(predicts_base)

[Prediction(uid=3, iid=1, r_ui=0, est=2.727776517381798, details={'was_impossible': False}),
 Prediction(uid=3, iid=2, r_ui=0, est=2.574367620672293, details={'was_impossible': False}),
 Prediction(uid=3, iid=23, r_ui=0, est=2.5728486563114514, details={'was_impossible': False})]

In [147]:
predicts_base = [(3,1,0),(3,2,0),(3,23,0)]
predictions =algo.test(predicts_base)
for uid, iid, true_r, est, _ in predictions:
    #print(_['actual_k'])
    print(est)


2.727776517381798
2.574367620672293
2.5728486563114514


In [148]:
predicts = []
def get_predicts():
    predictions =algo.test(predicts)
    for uid, iid, true_r, est, _ in predictions:
        predicts[iid].append((uid, est))
    return predicts
predicts = get_predicts()


In [149]:
predicts

[]

In [ ]:
np.float32

### 获取所有的每一个用户到item 的rating

### MF 矩阵分解（一阶版本的FM） 可以用SVD 或者梯度下降GD  求解   PMF 基于概率的矩阵分解，正态分布

- [推荐系统算法学习（一）——协同过滤(CF) MF FM FFM](https://blog.csdn.net/lmm6895071/article/details/75688936)
- [从SVD到推荐系统](https://www.cnblogs.com/bjwu/p/9358777.html)
- [降维方法PCA与SVD的联系与区别](https://www.cnblogs.com/bjwu/p/9280492.html)


In [154]:
# build similarity matrix
similarity_matrix = np.ndarray(shape=(userNo, movieNo), dtype=np.float32)
for i in range(userNo):
    for j in range(movieNo):
        similarity_matrix[i][j] = algo.predict(i,j).est
        

In [155]:
similarity_matrix.dtype

dtype('float32')

In [60]:
similarity_matrix[0][1]

3

In [76]:
predicts = pd.DataFrame(similarity_matrix)


In [77]:
np.argsort(similarity_matrix[1],axis=0)

array([7346, 5137, 9444, ..., 4643, 8631, 5726], dtype=int64)

In [78]:
similarity_matrix[1].argsort()[::-1][1]

8631

In [83]:
similarity_matrix.shape

(611, 9742)

In [85]:
similarity_matrix

array([[3, 3, 3, ..., 3, 3, 3],
       [4, 4, 4, ..., 4, 4, 4],
       [3, 3, 3, ..., 3, 3, 4],
       ...,
       [3, 2, 2, ..., 3, 3, 3],
       [3, 3, 3, ..., 3, 3, 3],
       [4, 3, 3, ..., 3, 3, 4]])

In [86]:
similarity_matrix[0]


array([3, 3, 3, ..., 3, 3, 3])

In [93]:
#similarity_matrix[0].sort(key = lambda x : x[1], reverse = True)
similarity_matrix[0].argsort()[::-1]

array([ 314, 3638,  520, ...,  559, 1743, 7363], dtype=int64)

In [112]:
similarity_matrix[0,[314,3638,520,7363]]

array([4, 4, 4, 2])

### 预测

In [151]:
### 前20条数据
def recommend(movies):
    #print(u'您要想哪位用户进行推荐？请输入用户编号：')
    user_id = input(u'您要想哪位用户进行推荐？请输入用户编号：')
    sortedResult = similarity_matrix[int(user_id)-1].argsort()[::-1]
    # argsort()函数返回的是数组值从小到大的索引值; argsort()[::-1] 返回的是数组值从大到小的索引值
    print(u'为该用户推荐的评分最高的20部电影是：'.center(80, '='))
    # center() 返回一个原字符串居中,并使用空格填充至长度 width 的新字符串。默认填充字符为空格。
    idx = 0
    for i in sortedResult:
        print(u'评分: %.2f, 电影名: %s' % (similarity_matrix[int(user_id)-1,i], movies.iloc[i]['title']))
        idx += 1
        if idx == 20:
            break

In [156]:
recommend(movies_df)

您要想哪位用户进行推荐？请输入用户编号：1
==============================为该用户推荐的评分最高的20部电影是：===============================
评分: 4.10, 电影名: Shawshank Redemption, The (1994)
评分: 4.07, 电影名: Lawrence of Arabia (1962)
评分: 4.07, 电影名: Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964)
评分: 4.03, 电影名: Rear Window (1954)
评分: 4.02, 电影名: Fight Club (1999)
评分: 4.01, 电影名: Cool Hand Luke (1967)
评分: 4.01, 电影名: Godfather: Part II, The (1974)
评分: 4.01, 电影名: Godfather, The (1972)
评分: 4.00, 电影名: Usual Suspects, The (1995)
评分: 4.00, 电影名: Streetcar Named Desire, A (1951)
评分: 4.00, 电影名: Boondock Saints, The (2000)
评分: 4.00, 电影名: Apocalypse Now (1979)
评分: 4.00, 电影名: Philadelphia Story, The (1940)
评分: 3.99, 电影名: Departed, The (2006)
评分: 3.99, 电影名: Princess Bride, The (1987)
评分: 3.99, 电影名: Dark Knight, The (2008)
评分: 3.99, 电影名: Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981)
评分: 3.99, 电影名: Goodfellas (1990)
评分: 3.98, 电影名: Reservoir Dogs (1992)
评分: 3.98, 电影名: One Flew Over the 